platform: x64
clone_folder: c:\hazci
os: Visual Studio 2015
environment:
  GOPATH: c:\gopath
  MYENVVAR: "kittens"
  HAZCIPATH: c:\hazci
install:
  - set PATH=%GOPATH%\bin;c:\go\bin;C:\msys64\mingw64\bin;C:\msys64\usr\bin\;%PATH%

  - ps: $env:VERSION = "$(git describe --tags)" # eg. v1.2.3-14-abcd123
  - ps: $env:VERSION_SEMVER_BASIC = "$(git describe --tags $(git rev-list --tags --max-count=1))" # eg. v1.2.3
  # - ps: $env:VERSION_BASE_DIST = "$(echo $env:VERSION_SEMVER_BASIC |  sed 's/\(^v[0-9]*\.[0-9]*\.\)[0-9]*/\1/' <<< )" # eg. v1.2. (will append 'x' at deploy path)
  - ps: $env:VERSION_BASE_DIST = (env:VERSION_SEMVER_BASIC -replace '\([0-9]*\)$', '') # eg. v1.2. (will append 'x' at deploy path)

  - cd c:\hazci

  - echo %VERSION%
  - echo %VERSION_SEMVER_BASIC%
  - echo %VERSION_BASE_DIST%
  - echo %PATH%
  - echo %GOPATH%

  - go version
  - go env
  - go get golang.org/x/sys/windows

build_script:
  - 7z a readme.zip README.md
before_deploy:
  - ps: Get-FileHash readme.zip -Algorithm SHA256
  - ps: Get-FileHash readme.zip | Out-File readme.zip.sha256
deploy_script:
  - ps: $env:ARTIFACTORY_URL = "little"
  - ps: $env:ARTIFACTORY_USER = "white"
  - ps: $env:ARTIFACTORY_APIKEY = "kitten"
  - curl -sL https://getcli.jfrog.io | bash
  - ps: >-
      If (($env:APPVEYOR_REPO_NAME -eq 'whilei/hazci') -and (($env:APPVEYOR_REPO_BRANCH -eq 'master') -or ($env:APPVEYOR_REPO_TAG -eq 'true'))) {
        .\jfrog.exe --help
        echo "somewh/ere/$env:VERSION_SEMVER_BASIC/"
        echo "somewhere/$env:VERSION_SEMVER_BASICx/"
        echo "some/where/$env:VERSION_BASE_DIST\x/"
        echo "some/where/$env:VERSION_BASE_DISTx/"
        echo "some/where/($env:VERSION_BASE_DIST)x/"
      }
