platform: x64
clone_folder: c:\hazci
os: Visual Studio 2015
environment:
  GOPATH: c:\gopath
  MYENVVAR: "kittens"
  HAZCIPATH: c:\hazci
install:
  - set PATH=%GOPATH%\bin;c:\go\bin;C:\msys64\mingw64\bin;C:\msys64\usr\bin\;%PATH%

  - ps: $env:VERSION = "$(git describe --tags)" # eg. v1.2.3-14-abcd123
  - ps: $env:VERSION_SEMVER_BASIC = "$(git describe --tags $(git rev-list --tags --max-count=1))" # eg. v1.2.3
  - ps: $env:VERSION_BASE_DIST = "$(echo $env:VERSION_SEMVER_BASIC | sed 's/\(^v[0-9]*\.[0-9]*\.\)[0-9]*/\1/')" # eg. v1.2. (will append 'x' at deploy path)

  - cd c:\hazci

  - echo %VERSION%
  - echo %VERSION_SEMVER_BASIC%
  - echo %VERSION_BASE_DIST%
  - echo %PATH%
  - echo %GOPATH%

  - go version
  - go env
  - go get golang.org/x/sys/windows

build_script:
  - 7z a readme.zip README.md
before_deploy:
  - certUtil -hashfile readme.zip SHA256 > readme-%VERSION%.zip.sha256
  - ps: >- 
      $sha256 = (Get-Content readme-$env:VERSION.zip.sha256)
      Write-Host -ForegroundColor Yellow -Message "sha256(readme-$env:VERSION.zip.sha256) = $sha256"
deploy_script:
  - ps: $env:ARTIFACTORY_URL = "little"
  - ps: $env:ARTIFACTORY_USER = "white"
  - ps: $env:ARTIFACTORY_APIKEY = "kitten"
  - ps: >-
      If (($env:APPVEYOR_REPO_NAME -eq 'whilei/hazci') -and (($env:APPVEYOR_REPO_BRANCH -eq 'master') -or ($env:APPVEYOR_REPO_TAG -eq 'true'))) {
        curl -fL https://getcli.jfrog.io | sh
        jfrog.exe --help
        echo "some/where/$env:VERSION_BASE_DISTx/"
        jfrog.exe config --url $env:ARTIFACTORY_URL --user $env:ARTIFACTORY_USER --apikey $env:ARTIFACTORY_APIKEY --interactive=false
        jfrog.exe rt upload "readme-*" "some/where/$env:VERSION_BASE_DISTx/"
      }
